CREATE TABLE tracks (
  id SERIAL PRIMARY KEY,
  song_id INT NOT NULL,
  owner_id INT NOT NULL,
  download_url VARCHAR NOT NULL,
  title VARCHAR NOT NULL,
  artist VARCHAR NOT NULL,
  duration_sec INT NOT NULL DEFAULT 0,
  likes_count INT NOT NULL DEFAULT 0,
  listens_count INT NOT NULL DEFAULT 1,
  UNIQUE (song_id, owner_id)
);

CREATE TABLE user_tracks (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
  track_id INT REFERENCES tracks (id) ON DELETE CASCADE NOT NULL,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE user_likes (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
  track_id INT REFERENCES tracks (id) ON DELETE CASCADE NOT NULL,
  liked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
